- id: Qwen3_6_27B
  name: "Qwen3.6-27B"
  model: "Qwen3.6-27B"
  task: TextToText
  default: true
  modified_at: "2026-04-22T15:59:03.844554+00:00"
  digest: 19a2f4733a863088bc06665bf307dca95f7d4370b4d8690340cdff9992fe48c6
  size: 35325163744
  details:
    format: gguf
    gguf_file: "/models/qwen3.6/27b/ud-q6_k_xl.gguf"
    family: qwen
    families:
      - qwen
    parameter_size: 26.9B
    quantization_level: Q6_K_XL
    precision: int4
    dtype: int4
    specialization: Text
    size: 35325163744
    original_ctx: 2048
    clip_model_path: /models/qwen3.6/27b/mmproj.gguf
  parameters:
    num_ctx: 200000
    repeat_last_n: 64
    repeat_penalty: 0.5
    temperature: 0.7
    seed: -1
    num_predict: -1
    top_k: 20
    top_p: 0.90
    min_p: 0.01
    max_tokens: 65536
    n_parts: -1
    batch_size: 2048
    micro_batch_size: 2048
    n_gpu_layers: -1
    think: True
    reasoning_budget: 8192
    kv_on_cpu: False
    # tensor_split: "0,1,1"
    main_gpu: 2
    # n_cpu_moe: 10
    # ctx_size_reduction_limit: 1.0
    parallel: 8
    is_default: True
  pipeline: llama
  lora_weights: []
  provider: llama_cpp

- id: Qwen3_6_35B_A3B
  name: "Qwen3.6-35B-A3B"
  model: "Qwen3.6-35B-A3B"
  task: TextToText
  modified_at: "2026-04-19T16:47:38.874251+00:00"
  digest: b762215c5f507f4865df4ac3d1afa803828afa41e05ecac3fac431a67bbd88e8
  size: 38451182560
  details:
    format: gguf
    gguf_file: "/models/qwen3.6/35b-a3b/ud-q6_k_xl.gguf"
    family: qwen
    families:
      - qwen
    parameter_size: 34.7B
    quantization_level: Q6_K_XL
    precision: int4
    dtype: int4
    specialization: Text
    size: 38451182560
    original_ctx: 262144
    n_layers: 40
    hidden_size: 2048
    n_heads: 16
    n_kv_heads: 2
  parameters:
    num_ctx: 200000
    repeat_last_n: -1
    repeat_penalty: 0
    temperature: 0.7
    seed: -1
    num_predict: -1
    top_k: 20
    top_p: 0.95
    min_p: 0.05
    max_tokens: -1
    n_parts: -1
    batch_size: 2048
    micro_batch_size: 1024
    n_gpu_layers: -1
    think: False
    kv_on_cpu: True
    # tensor_split: "0,1,1"
    main_gpu: 1
    # n_cpu_moe: 10
  pipeline: llama
  lora_weights: []
  provider: llama_cpp
# - id: Qwen3_5_9B
#   name: "Qwen3.5-9B"
#   model: "Qwen3.5-9B"
#   task: TextToText
#   modified_at: "2026-04-03T17:42:00.692848+00:00"
#   digest: 8f0cb1e8e058e45c7d9676fcd4da2f08eb62ff537da747a6ffc7157c1f6a5684
#   size: 771092736
#   details:
#     format: gguf
#     gguf_file: "/models/qwen3.5/9b/ud-q_4_k_xl.gguf"
#     family: qwen
#     families:
#       - qwen
#     parameter_size: 752.4M
#     quantization_level: Q4_K_XL
#     precision: int4
#     dtype: int4
#     specialization: Text
#     size: 771092736
#     original_ctx: 2048
#   parameters:
#     num_ctx: 100000
#     repeat_last_n: 256
#     repeat_penalty: 1.1
#     temperature: 0.7
#     seed: -1
#     num_predict: -1
#     top_k: 20
#     top_p: 0.95
#     min_p: 0.05
#     max_tokens: 16384
#     n_parts: -1
#     batch_size: 4096
#     micro_batch_size: 4096
#     n_gpu_layers: -1
#     think: False
#     kv_on_cpu: True
#     # n_cpu_moe: 10
#   pipeline: llama
#   lora_weights: []
#   provider: llama_cpp

# - id: Qwen3_5_4B
#   name: "Qwen3.5-4B"
#   model: "Qwen3.5-4B"
#   task: TextToText
#   modified_at: "2026-04-03T17:42:00.692848+00:00"
#   digest: 8f0cb1e8e058e45c7d9676fcd4da2f08eb62ff537da747a6ffc7157c1f6a5684
#   size: 771092736
#   details:
#     format: gguf
#     gguf_file: "/models/qwen3.5/4b/ud-q_4_k_xl.gguf"
#     family: qwen
#     families:
#       - qwen
#     parameter_size: 752.4M
#     quantization_level: Q4_K_XL
#     precision: int4
#     dtype: int4
#     specialization: Text
#     size: 771092736
#     original_ctx: 2048
#   parameters:
#     num_ctx: 100000
#     repeat_last_n: 256
#     repeat_penalty: 1.1
#     temperature: 0.7
#     seed: -1
#     num_predict: -1
#     top_k: 20
#     top_p: 0.95
#     min_p: 0.05
#     max_tokens: 16384
#     n_parts: -1
#     batch_size: 4096
#     micro_batch_size: 4096
#     n_gpu_layers: -1
#     think: False
#     kv_on_cpu: True
#     # n_cpu_moe: 10
#   pipeline: llama
#   lora_weights: []
#   provider: llama_cpp
