apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-llmmllab-runner
spec:
  storageClassName: ""
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /models
    type: Directory
  claimRef:
    namespace: llmmllab
    name: models
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - lsnode-3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models
  namespace: llmmllab
spec:
  storageClassName: ""
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Gi
